server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://sjc1.clusters.zeabur.com:30478/zeabur}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:235R7o6nPi8uZDxlEhMk49rSj0zqNyt1}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: localhost

jetcache:
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      uri: redis://127.0.0.1:6379/

# 添加 jarfile 配置，确保容器能找到你的 .jar 文件
jarfile: /src/lottery-admin/target/lottery-admin-0.0.1-SNAPSHOT.jar
