server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://sjc1.clusters.zeabur.com:30478/zeabur}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:235R7o6nPi8uZDxlEhMk49rSj0zqNyt1}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  # 注释掉 Redis 配置
  # redis:
  #   port: 6379
  #   host: localhost
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

jetcache:
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  # 禁用远程缓存
  remote:
    default:
      type: none

# 删除无效的 jarfile 配置
