server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql.zeabur.internal:3306/zeabur?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 235R7o6nPi8uZDxlEhMk49rSj0zqNyt1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update   # 第一次启动会自动建表，之后建议改成 validate

  thymeleaf:
    cache: false

  # 禁用 Redis，避免在 Zeabur 没有 Redis 时启动报错
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

jetcache:
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: none   # 禁用远程缓存
